[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/odds"
  to = "/.netlify/functions/odds"
  status = 200

[[redirects]]
  from = "/api/db"
  to = "/.netlify/functions/db"
  status = 200
